<?php get_header(); ?>
<div class="rb-nav-pusher"></div>
<div class="rb-section-container">
    <div class="rb-container">
        <h1>Autotype</h1>
        <h2>Static Element</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
        <h2>Static Element</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
        <h2>Static Element</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
        <h2>Start autotype when element scrolls into view</h2>
        <p class="rb-autotype" id="autotype-one">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
        <h2>Start autotype when element scrolls into view</h2>
        <p class="rb-autotype" id="autotype-two">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
        <h2>Start autotype when element scrolls into view</h2>
        <p class="rb-autotype" id="autotype-three">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
        <h2>Start autotype when element scrolls into view</h2>
        <p class="rb-autotype" id="autotype-four">Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus tempora harum beatae totam maiores error asperiores nesciunt, nulla, fuga, quod rerum impedit! Adipisci fugit sed ex, dicta incidunt accusamus at. Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt quia in adipisci est officia reiciendis ullam necessitatibus accusamus repudiandae ratione porro illum quis nam quod, dolore molestiae eos modi? Similique. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Pariatur maiores assumenda illo vero recusandae totam in alias nobis possimus numquam dolor temporibus adipisci, architecto similique voluptas eveniet sed? Magni, optio.</p>
    </div>
</div>
<?php get_footer(); ?>